name: wf-cd-release
on:
  push:
    branches:
      - release
jobs:
  build-job-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository On the Runner
        uses: actions/checkout@v4
        with:
          ref: "${{github.ref}}"
      - name: Build Static Wesbite With Parcel
        run: npx parcel build "./src/index.html" --dist-dir "./rel-dist" --public-url "./"
      - name:  Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./rel-dist"
          name: "build-artifact-release"
  deploy-job-release:
    needs: "build-job-release"
    runs-on: ubuntu-latest
    environment:
      name: "stagging-env"
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Website On GH-Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-release"
          token: "${{github.token}}" #token hai tou username aur password dene ki zroorat ni it will authentivate itself

    






